### ISSUE TITLE
Readmeの日本語化

### ISSUE THREAD

**Issue by kuromike0629** [kuromike0629/genesis#10]
Readmeは最初自動生成だったから英語にしたけどやっぱり、日本語の方がいいかな？

または、どっちも付け加えるのもいいけどどうですかね？

**Comment by Hato6502** [comment]
英語は必要だと思う。

まだ僕はREADME.md書いてないけど、勉強のつもりでbuttonのreadmeを英語で書く予定

**Comment by kuromike0629** [comment]
了解
一応ドキュメントをいじる他のブランチをきってそっちからreadmeやドキュメントは作って欲しいかな。

あとはwikiを作ることもできるからreadmeは最低限のインストール方法を記述して、残りはwikiで行うのが推奨だけどどうかな？

**Comment by kuromike0629** [comment]
じゃあとりあえず方針としてreadmeは英語で書いていく方針で！

**Comment by Hato6502** [comment]
Okay. 
I had written README.md of button device driver in English. 
Please correct when you'll have viewed: button branch /dev/button/README.md. 

了解。
とりあえず、buttonのREADMEを英語で書いてみた。
中身見た時に、添削お願いします。

**Comment by Hato6502** [comment]
I made docments branch and Wiki, and I'll write English documents in this branch. 
※I'm wiriting also issue comments in English, you feel nuisance? 

docmentsブランチとWikiを作ったので、こっちで英語の文章を書いていきます。
※issuesまでなぜか英語で書いてるけど、つきあってくれる？

**Comment by kuromike0629** [comment]
Yes of couse! I think that's good idea.
I will try to write documents and issues in English.
It will be fine.
