### ISSUE TITLE
リポジトリ名の変更

### ISSUE THREAD

**Issue by kuromike0629** [kuromike0629/genesis#3]
リポジトリ名を変更したので確認と再cloneをよろしく

Genesis => genesis

変更に関して、ローカルのリポジトリを変更する場合はこっちのウェブサイトを参考によろしく

http://d.hatena.ne.jp/MonteCut/20110819/1313742250

**Comment by kuromike0629** [comment]
Rubyの命名規則について考慮し忘れてたから、一旦すべてのファイル命名規則をなおしたので確認よろしく

あと全体で必要だった変更だからmasterにマージしちゃったからそっちからもう一回cloneをお願いします。

**Comment by Hato6502** [comment]
ok
