### ISSUE TITLE
ゲームパッケージ仕様について

### ISSUE THREAD

**Issue by kuromike0629** [kuromike0629/genesis#5]
ゲームを配布するパッケージ形式を決めたいんだけど。
Javaみたいに、ファイルをまとめてzip形式でまとめて拡張子を.genにする。
ディレクトリの一番上にGenesisfileという。起動用コードを含める。
という仕様でどうかな？

例としては以下みたいなディレクトリ構造かな
Genesisファイルは基本的にshell scriptで記述
ファイルの一番上には、#!/bin/shを記述すること。

って感じかな？

[パッケージ名].gen
-Genesisfile
-lib
-img

etc...

**Comment by Hato6502** [comment]
追加仕様として、任意でメニューアイコン
をzipに入れるのはどう？

**Comment by kuromike0629** [comment]
それはいいね！
それじゃ一緒にthumbnail.pngをパッケージディレクトリにいれるって感じで！

変更後はこんな感じでどう？

[パッケージ名].gen
/Genesisfile
/thumbnail.png
-lib
-img

**Comment by Hato6502** [comment]
いいと思うよ

**Comment by kuromike0629** [comment]
一応サムネイル画像の画素は64×64ピクセルでどうかな？

それだと、アイコンを作るソフトで作れるし、サイズ的にちょうどいいと思う！

**Comment by kuromike0629** [comment]
パッケージの拡張子だけ.genだと他とかぶるから.gnにするね

**Comment by kuromike0629** [comment]
パッケージを作成して、プルリクエストを出したから、コードレビューをおねがい！
