### ISSUE TITLE
ゲームパッケージの置き場所

### ISSUE THREAD

**Issue by kuromike0629** [kuromike0629/genesis#7]
ゲームパッケージの置き場所を定義したい。

場所の候補としては以下の通り
1.リポジトリ以下に /games をおく。
2.#5にある設定ファイルにゲームへのルートファイルを指定できるようにする。

どっちがいいかな？

**Comment by Hato6502** [comment]
1かな

**Comment by kuromike0629** [comment]
了解！
じゃあ定義してサンプルゲームを設置しておくね！

ブランチ名はsampleで
